// Generates js/config.js from Vercel environment variables at build time.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ENV_KEYS = [
  "FIREBASE_API_KEY",
  "FIREBASE_AUTH_DOMAIN",
  "FIREBASE_PROJECT_ID",
  "FIREBASE_STORAGE_BUCKET",
  "FIREBASE_MESSAGING_SENDER_ID",
  "FIREBASE_APP_ID",
  "SETTINGS_PASSWORD",
];

const missing = ENV_KEYS.filter((key) => !process.env[key]);
if (missing.length > 0) {
  console.warn(
    `generateConfig: missing environment variables: ${missing.join(", ")} — js/config.js will have blank values for these and the app will fall back to local-only mode.`
  );
}

const entries = ENV_KEYS.map(
  (key) => `  ${key}: ${JSON.stringify(process.env[key] ?? "")}`
).join(",\n");

const output = `// Auto-generated by scripts/generateConfig.js from Vercel environment variables. Do not edit directly.
window.ECF_CONFIG = {
${entries}
};
`;

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(__dirname, "..", "js", "config.js");
writeFileSync(outPath, output);
console.log(`generateConfig: wrote ${outPath}`);
